name: qack
description: A translation app for learning Chinese and English through speaking.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  get_it: ^8.0.3
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  sentry_flutter: ^8.14.2
  speech_to_text: ^7.0.0
  http_client:
    path: ./packages/http_client
  json_annotation: ^4.9.0
  auto_size_text: ^3.0.0
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.2
  bottom_bar: ^2.0.3


dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/.env
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Nunito/Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito/Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito/Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito/Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito/ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito/Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/BlackItalic.ttf
          weight: 900
          style: italic